stages:
- stage: Deploy
  jobs:
  - deployment: DeployWeb
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn’t exist
    environment: 'Dev'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '763da4b0-f0c6-4b64-bb61-74588b2a10ff'
              pipeline: '8'
              specificBuildWithTriggering: true
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(subscriptionConnectionName)'
              appType: 'webApp'
              WebAppName: 'alexeypocprodapp01'
              deployToSlotOrASE: true
              ResourceGroupName: '$(webAppResourceGroup)'
              SlotName: 'production'
              packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'

